# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"?\n\tProductps\x12\x12\n\nid_product\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\"*\n\x13TransactionResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32w\n\x0eProductService\x12\x30\n\nAddProduct\x12\n.Productps\x1a\x14.TransactionResponse\"\x00\x12\x33\n\rDeleteProduct\x12\n.Productps\x1a\x14.TransactionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTPS._serialized_start=17
  _PRODUCTPS._serialized_end=80
  _TRANSACTIONRESPONSE._serialized_start=82
  _TRANSACTIONRESPONSE._serialized_end=124
  _PRODUCTSERVICE._serialized_start=126
  _PRODUCTSERVICE._serialized_end=245
# @@protoc_insertion_point(module_scope)
