# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"\x1e\n\tInventory\x12\x11\n\tInventory\x18\x08 \x03(\x05\"\t\n\x07Request2:\n\x10InventoryService\x12&\n\x0cGetInventory\x12\x08.Request\x1a\n.Inventory\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVENTORY._serialized_start=17
  _INVENTORY._serialized_end=47
  _REQUEST._serialized_start=49
  _REQUEST._serialized_end=58
  _INVENTORYSERVICE._serialized_start=60
  _INVENTORYSERVICE._serialized_end=118
# @@protoc_insertion_point(module_scope)
